export interface Costume {
  id: string;
  name: string;
  category: "avengers" | "dc" | "anime" | "fantasy" | "scifi" | "sports" | "music" | "gaming" | "movies" | "meme" | "crypto" | "historical" | "holiday";
  emoji: string;
  prompt: string;
  accent: string;
  description: string;
}

export const COSTUME_CATEGORIES = [
  { id: "all", label: "All" },
  { id: "avengers", label: "⚡ Marvel" },
  { id: "dc", label: "🦇 DC" },
  { id: "anime", label: "🌸 Anime" },
  { id: "fantasy", label: "🔮 Fantasy" },
  { id: "scifi", label: "🚀 Sci-Fi" },
  { id: "sports", label: "⚽ Sports" },
  { id: "music", label: "🎵 Music" },
  { id: "gaming", label: "🎮 Gaming" },
  { id: "movies", label: "🎬 Movies" },
  { id: "meme", label: "😂 Meme" },
  { id: "crypto", label: "🪙 Crypto" },
  { id: "historical", label: "🏛️ Historical" },
  { id: "holiday", label: "🎄 Holiday" },
] as const;

export const COSTUMES: Costume[] = [
  // ── MARVEL ──────────────────────────────────────────────
  {
    id: "iron-man",
    name: "Iron Man",
    category: "avengers",
    emoji: "🦾",
    accent: "#ef4444",
    description: "Red & gold helmet",
    prompt: "a small Iron Man red and gold helmet placed on the cat's head",
  },
  {
    id: "thor",
    name: "Thor",
    category: "avengers",
    emoji: "⚡",
    accent: "#3b82f6",
    description: "Thor's winged helmet",
    prompt: "a small silver Viking Thor winged helmet placed on the cat's head",
  },
  {
    id: "captain-america",
    name: "Captain America",
    category: "avengers",
    emoji: "🛡️",
    accent: "#1d4ed8",
    description: "Vibranium shield",
    prompt: "a small Captain America round blue shield with a white star leaning against the cat or held in one paw",
  },
  {
    id: "thanos",
    name: "Thanos",
    category: "avengers",
    emoji: "💜",
    accent: "#7c3aed",
    description: "Infinity Gauntlet",
    prompt: "a golden Infinity Gauntlet glove with glowing colored stones placed on one of the cat's paws",
  },
  {
    id: "spider-man",
    name: "Spider-Man",
    category: "avengers",
    emoji: "🕸️",
    accent: "#dc2626",
    description: "Spidey mask",
    prompt: "a small red and blue Spider-Man mask placed on the cat's head",
  },
  {
    id: "hulk",
    name: "Hulk",
    category: "avengers",
    emoji: "💪",
    accent: "#16a34a",
    description: "Hulk fists",
    prompt: "two small green Hulk foam fist props placed over the cat's two front paws",
  },
  {
    id: "black-widow",
    name: "Black Widow",
    category: "avengers",
    emoji: "🕷️",
    accent: "#6b7280",
    description: "Red Widow belt",
    prompt: "a black leather spy utility belt with a small red hourglass emblem placed around the cat's waist",
  },
  {
    id: "wolverine",
    name: "Wolverine",
    category: "avengers",
    emoji: "🗡️",
    accent: "#f59e0b",
    description: "Adamantium claws",
    prompt: "three small silver adamantium claws extending from one of the cat's paws like Wolverine",
  },
  {
    id: "doctor-strange",
    name: "Doctor Strange",
    category: "avengers",
    emoji: "🌀",
    accent: "#6366f1",
    description: "Cloak of Levitation",
    prompt: "a small red Cloak of Levitation draped around the cat's shoulders like Doctor Strange",
  },
  {
    id: "black-panther",
    name: "Black Panther",
    category: "avengers",
    emoji: "🐾",
    accent: "#7c3aed",
    description: "Vibranium mask",
    prompt: "a small Black Panther silver and black vibranium mask placed on the cat's head",
  },

  // ── DC ──────────────────────────────────────────────────
  {
    id: "batman",
    name: "Batman",
    category: "dc",
    emoji: "🦇",
    accent: "#1f2937",
    description: "Bat cowl",
    prompt: "a small black Batman cowl with pointy ears placed on the cat's head",
  },
  {
    id: "superman",
    name: "Superman",
    category: "dc",
    emoji: "🦸",
    accent: "#2563eb",
    description: "Super cape",
    prompt: "a small red Superman cape with the S shield emblem placed around the cat's neck and flowing behind",
  },
  {
    id: "wonder-woman",
    name: "Wonder Woman",
    category: "dc",
    emoji: "⭐",
    accent: "#dc2626",
    description: "Golden tiara",
    prompt: "a small golden Wonder Woman tiara with a red star placed on the cat's head",
  },
  {
    id: "joker",
    name: "The Joker",
    category: "dc",
    emoji: "🃏",
    accent: "#16a34a",
    description: "Joker hat",
    prompt: "a small purple Joker top hat placed on the cat's head",
  },
  {
    id: "aquaman",
    name: "Aquaman",
    category: "dc",
    emoji: "🔱",
    accent: "#0ea5e9",
    description: "Atlantis trident",
    prompt: "a small golden Aquaman trident prop held in the cat's paw",
  },
  {
    id: "flash",
    name: "The Flash",
    category: "dc",
    emoji: "⚡",
    accent: "#dc2626",
    description: "Flash helmet",
    prompt: "a small red Flash helmet with golden lightning bolt wings placed on the cat's head",
  },

  // ── ANIME ───────────────────────────────────────────────
  {
    id: "naruto",
    name: "Naruto",
    category: "anime",
    emoji: "🍜",
    accent: "#f97316",
    description: "Ninja headband",
    prompt: "a Naruto ninja metal headband with the Konoha leaf symbol placed on the cat's forehead",
  },
  {
    id: "goku",
    name: "Goku",
    category: "anime",
    emoji: "🐉",
    accent: "#f59e0b",
    description: "Super Saiyan hair",
    prompt: "a spiky golden Super Saiyan hair wig placed on the cat's head",
  },
  {
    id: "sailor-moon",
    name: "Sailor Moon",
    category: "anime",
    emoji: "🌙",
    accent: "#ec4899",
    description: "Moon tiara",
    prompt: "a small golden Sailor Moon crescent moon tiara placed on the cat's forehead",
  },
  {
    id: "luffy",
    name: "Luffy",
    category: "anime",
    emoji: "🏴‍☠️",
    accent: "#ef4444",
    description: "Straw hat",
    prompt: "a small woven straw hat placed on top of the cat's head",
  },
  {
    id: "demon-slayer",
    name: "Tanjiro",
    category: "anime",
    emoji: "🌊",
    accent: "#0ea5e9",
    description: "Nichirin blade",
    prompt: "a small red Nichirin demon slayer sword prop placed beside the cat or held in one paw",
  },
  {
    id: "vegeta",
    name: "Vegeta",
    category: "anime",
    emoji: "👑",
    accent: "#a855f7",
    description: "Saiyan armor",
    prompt: "a small white Saiyan Prince armor chest piece placed on the cat's torso",
  },
  {
    id: "pikachu",
    name: "Pikachu",
    category: "anime",
    emoji: "⚡",
    accent: "#f59e0b",
    description: "Pikachu ears",
    prompt: "small yellow Pikachu ear accessories placed on top of the cat's head",
  },
  {
    id: "totoro",
    name: "Totoro",
    category: "anime",
    emoji: "🌿",
    accent: "#6b7280",
    description: "Totoro leaf",
    prompt: "a large green leaf umbrella prop like Totoro's held over the cat's head",
  },
  {
    id: "one-punch",
    name: "One Punch Man",
    category: "anime",
    emoji: "👊",
    accent: "#f59e0b",
    description: "Hero cape",
    prompt: "a small yellow One Punch Man hero cape and white suit placed on the cat's body",
  },
  {
    id: "itachi",
    name: "Itachi",
    category: "anime",
    emoji: "🌙",
    accent: "#7c3aed",
    description: "Akatsuki cloak",
    prompt: "a small black Akatsuki cloak with red cloud patterns draped around the cat",
  },

  // ── FANTASY ─────────────────────────────────────────────
  {
    id: "wizard-hat",
    name: "Dark Wizard",
    category: "fantasy",
    emoji: "🧙",
    accent: "#6366f1",
    description: "Wizard hat",
    prompt: "a tall dark wizard pointed hat with gold stars and moons placed on the cat's head",
  },
  {
    id: "vampire",
    name: "Vampire",
    category: "fantasy",
    emoji: "🧛",
    accent: "#dc2626",
    description: "Vampire cape",
    prompt: "a dramatic black vampire cape with a red collar placed around the cat's neck and shoulders",
  },
  {
    id: "knight-helmet",
    name: "Knight",
    category: "fantasy",
    emoji: "⚔️",
    accent: "#9ca3af",
    description: "Knight helmet",
    prompt: "a small shining silver medieval knight helmet placed on the cat's head",
  },
  {
    id: "crown",
    name: "Royal Crown",
    category: "fantasy",
    emoji: "👑",
    accent: "#f59e0b",
    description: "Gold crown",
    prompt: "a shiny gold royal crown placed on top of the cat's head",
  },
  {
    id: "wizard-staff",
    name: "Wizard Staff",
    category: "fantasy",
    emoji: "🔮",
    accent: "#8b5cf6",
    description: "Glowing staff",
    prompt: "a glowing magical wizard staff with a crystal orb on top leaning against the cat or held in one paw",
  },
  {
    id: "dragon-egg",
    name: "Dragon Rider",
    category: "fantasy",
    emoji: "🐲",
    accent: "#10b981",
    description: "Dragon egg",
    prompt: "a small colorful speckled dragon egg prop placed in front of the cat as if the cat is guarding it",
  },
  {
    id: "witch-hat",
    name: "Witch",
    category: "fantasy",
    emoji: "🧹",
    accent: "#4b5563",
    description: "Witch hat",
    prompt: "a black witch hat with a buckle placed on the cat's head",
  },
  {
    id: "fairy-wings",
    name: "Fairy",
    category: "fantasy",
    emoji: "🧚",
    accent: "#ec4899",
    description: "Fairy wings",
    prompt: "small translucent glittery fairy wings attached to the cat's back",
  },
  {
    id: "elf-ears",
    name: "Elf",
    category: "fantasy",
    emoji: "🏹",
    accent: "#84cc16",
    description: "Elf ears",
    prompt: "small pointed elf ear accessories placed on the sides of the cat's head",
  },
  {
    id: "pirate-hat",
    name: "Pirate",
    category: "fantasy",
    emoji: "☠️",
    accent: "#1f2937",
    description: "Pirate hat",
    prompt: "a small black pirate tricorn hat with a skull and crossbones placed on the cat's head",
  },

  // ── SCI-FI ──────────────────────────────────────────────
  {
    id: "jedi",
    name: "Jedi Master",
    category: "scifi",
    emoji: "⚔️",
    accent: "#22d3ee",
    description: "Blue lightsaber",
    prompt: "a glowing blue lightsaber prop placed held in the cat's paw or leaning beside it",
  },
  {
    id: "sith",
    name: "Sith Lord",
    category: "scifi",
    emoji: "🔴",
    accent: "#dc2626",
    description: "Red lightsaber",
    prompt: "a glowing red Sith lightsaber prop placed held in the cat's paw",
  },
  {
    id: "astronaut",
    name: "Astronaut",
    category: "scifi",
    emoji: "🚀",
    accent: "#64748b",
    description: "Space helmet",
    prompt: "a white NASA astronaut helmet placed on the cat's head",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    category: "scifi",
    emoji: "🤖",
    accent: "#f43f5e",
    description: "Neon visor",
    prompt: "futuristic neon-lit cyberpunk visor sunglasses placed on the cat's face",
  },
  {
    id: "mandalorian",
    name: "Mandalorian",
    category: "scifi",
    emoji: "🪖",
    accent: "#b45309",
    description: "Beskar helmet",
    prompt: "a Mandalorian silver beskar T-visor helmet placed on the cat's head",
  },
  {
    id: "stormtrooper",
    name: "Stormtrooper",
    category: "scifi",
    emoji: "🤖",
    accent: "#f1f5f9",
    description: "Stormtrooper helmet",
    prompt: "a white Imperial Stormtrooper helmet placed on the cat's head",
  },
  {
    id: "robot",
    name: "Robot",
    category: "scifi",
    emoji: "🤖",
    accent: "#94a3b8",
    description: "Robot helmet",
    prompt: "a chrome metallic robot head helmet with glowing LED eyes placed on the cat's head",
  },
  {
    id: "alien",
    name: "Alien",
    category: "scifi",
    emoji: "👽",
    accent: "#4ade80",
    description: "Alien antennae",
    prompt: "two small green alien antennae headband accessories placed on the cat's head",
  },

  // ── SPORTS ──────────────────────────────────────────────
  {
    id: "football-jersey",
    name: "Football Star",
    category: "sports",
    emoji: "⚽",
    accent: "#16a34a",
    description: "Football jersey",
    prompt: "a small football jersey placed on the cat's torso",
  },
  {
    id: "boxing-gloves",
    name: "Boxer",
    category: "sports",
    emoji: "🥊",
    accent: "#ef4444",
    description: "Boxing gloves",
    prompt: "two small red boxing gloves placed on the cat's two front paws",
  },
  {
    id: "baseball-cap",
    name: "Baseball Player",
    category: "sports",
    emoji: "⚾",
    accent: "#1d4ed8",
    description: "Baseball cap",
    prompt: "a small baseball cap placed on the cat's head",
  },
  {
    id: "gold-medal",
    name: "Gold Medalist",
    category: "sports",
    emoji: "🥇",
    accent: "#f59e0b",
    description: "Olympic gold medal",
    prompt: "an Olympic gold medal on a ribbon hung around the cat's neck",
  },
  {
    id: "tennis-racket",
    name: "Tennis Pro",
    category: "sports",
    emoji: "🎾",
    accent: "#84cc16",
    description: "Tennis racket",
    prompt: "a small tennis racket prop placed held in the cat's paw",
  },
  {
    id: "football-helmet",
    name: "NFL Player",
    category: "sports",
    emoji: "🏈",
    accent: "#7c3aed",
    description: "Football helmet",
    prompt: "a small American football helmet placed on the cat's head",
  },
  {
    id: "basketball",
    name: "NBA Star",
    category: "sports",
    emoji: "🏀",
    accent: "#ea580c",
    description: "Basketball",
    prompt: "a small basketball prop balanced on one of the cat's paws",
  },
  {
    id: "surfboard",
    name: "Surfer",
    category: "sports",
    emoji: "🏄",
    accent: "#0ea5e9",
    description: "Surf visor",
    prompt: "a colorful surf visor and lei flower garland placed on the cat's head and neck",
  },

  // ── MUSIC ───────────────────────────────────────────────
  {
    id: "dj-headphones",
    name: "DJ",
    category: "music",
    emoji: "🎧",
    accent: "#6366f1",
    description: "DJ headphones",
    prompt: "large DJ headphones placed over the cat's ears",
  },
  {
    id: "rock-star",
    name: "Rock Star",
    category: "music",
    emoji: "🎸",
    accent: "#ef4444",
    description: "Electric guitar",
    prompt: "a small electric guitar prop placed held in the cat's paws or leaning beside it",
  },
  {
    id: "top-hat",
    name: "Jazz Cat",
    category: "music",
    emoji: "🎷",
    accent: "#1f2937",
    description: "Jazz top hat",
    prompt: "a tall black top hat placed on the cat's head",
  },
  {
    id: "microphone",
    name: "Pop Star",
    category: "music",
    emoji: "🎤",
    accent: "#ec4899",
    description: "Stage mic",
    prompt: "a shiny chrome microphone prop held in one of the cat's paws",
  },
  {
    id: "cowboy-hat",
    name: "Country Star",
    category: "music",
    emoji: "🤠",
    accent: "#b45309",
    description: "Cowboy hat",
    prompt: "a brown cowboy hat placed on the cat's head",
  },
  {
    id: "viking-helmet",
    name: "Viking",
    category: "music",
    emoji: "🪖",
    accent: "#9ca3af",
    description: "Viking helmet",
    prompt: "a horned Viking warrior helmet placed on the cat's head",
  },

  // ── GAMING ──────────────────────────────────────────────
  {
    id: "mario-cap",
    name: "Mario",
    category: "gaming",
    emoji: "🍄",
    accent: "#ef4444",
    description: "Mario red cap",
    prompt: "a small red Mario Bros cap with a white M badge placed on the cat's head",
  },
  {
    id: "link-hat",
    name: "Link",
    category: "gaming",
    emoji: "🗡️",
    accent: "#16a34a",
    description: "Zelda green hat",
    prompt: "a small green Link elf hat from The Legend of Zelda placed on the cat's head",
  },
  {
    id: "master-sword",
    name: "Legend of Zelda",
    category: "gaming",
    emoji: "⚔️",
    accent: "#3b82f6",
    description: "Master Sword",
    prompt: "a small Master Sword from Zelda placed leaning beside the cat or held in one paw",
  },
  {
    id: "minecraft-pickaxe",
    name: "Miner",
    category: "gaming",
    emoji: "⛏️",
    accent: "#a16207",
    description: "Diamond pickaxe",
    prompt: "a small pixelated Minecraft diamond pickaxe prop held in the cat's paw",
  },
  {
    id: "among-us",
    name: "Among Us",
    category: "gaming",
    emoji: "🔴",
    accent: "#dc2626",
    description: "Crewmate helmet",
    prompt: "a small red Among Us crewmate space helmet placed on the cat's head",
  },
  {
    id: "ps5-controller",
    name: "Gamer",
    category: "gaming",
    emoji: "🎮",
    accent: "#3b82f6",
    description: "PS5 controller",
    prompt: "a small PlayStation 5 DualSense controller placed held in the cat's paws",
  },
  {
    id: "pac-man",
    name: "Pac-Man",
    category: "gaming",
    emoji: "👾",
    accent: "#f59e0b",
    description: "Pac-Man bow",
    prompt: "a yellow Pac-Man shaped bow accessory placed on the cat's head",
  },
  {
    id: "pokemon-trainer",
    name: "Pokémon Trainer",
    category: "gaming",
    emoji: "⚽",
    accent: "#dc2626",
    description: "Trainer cap",
    prompt: "a red Pokémon trainer cap placed on the cat's head",
  },

  // ── MOVIES ──────────────────────────────────────────────
  {
    id: "harry-potter",
    name: "Harry Potter",
    category: "movies",
    emoji: "🪄",
    accent: "#7c3aed",
    description: "Wizard wand",
    prompt: "a small Harry Potter wand prop held in the cat's paw and small round glasses placed on the cat's face",
  },
  {
    id: "indiana-jones",
    name: "Indiana Jones",
    category: "movies",
    emoji: "🎩",
    accent: "#b45309",
    description: "Fedora hat",
    prompt: "a brown Indiana Jones fedora hat placed on the cat's head",
  },
  {
    id: "sherlock",
    name: "Sherlock Holmes",
    category: "movies",
    emoji: "🔍",
    accent: "#4b5563",
    description: "Deerstalker hat",
    prompt: "a Sherlock Holmes deerstalker cap and small magnifying glass prop placed on the cat",
  },
  {
    id: "jack-sparrow",
    name: "Captain Jack",
    category: "movies",
    emoji: "🏴‍☠️",
    accent: "#b45309",
    description: "Pirate captain hat",
    prompt: "a black weathered pirate captain hat placed on the cat's head",
  },
  {
    id: "terminator",
    name: "Terminator",
    category: "movies",
    emoji: "🤖",
    accent: "#dc2626",
    description: "Red eye visor",
    prompt: "red glowing Terminator machine eye visor sunglasses placed on the cat's face",
  },
  {
    id: "ghostbusters",
    name: "Ghostbuster",
    category: "movies",
    emoji: "👻",
    accent: "#4ade80",
    description: "Ghost trap",
    prompt: "a small Ghostbusters proton pack prop and ghost trap placed beside the cat",
  },
  {
    id: "matrix",
    name: "The Matrix",
    category: "movies",
    emoji: "💊",
    accent: "#22c55e",
    description: "Matrix sunglasses",
    prompt: "small round black Matrix Neo sunglasses placed on the cat's face",
  },
  {
    id: "hobbit",
    name: "The Hobbit",
    category: "movies",
    emoji: "💍",
    accent: "#f59e0b",
    description: "The One Ring",
    prompt: "a small glowing golden One Ring from Lord of the Rings placed in one of the cat's paws",
  },

  // ── MEME ────────────────────────────────────────────────
  {
    id: "deal-with-it",
    name: "Deal With It",
    category: "meme",
    emoji: "😎",
    accent: "#1f2937",
    description: "Doge sunglasses",
    prompt: "pixelated 8-bit Deal With It sunglasses dropping onto the cat's face",
  },
  {
    id: "party-hat",
    name: "Party Time",
    category: "meme",
    emoji: "🎉",
    accent: "#f43f5e",
    description: "Party hat",
    prompt: "a colorful cone party hat placed on top of the cat's head with confetti around it",
  },
  {
    id: "graduation-cap",
    name: "Scholar",
    category: "meme",
    emoji: "🎓",
    accent: "#1f2937",
    description: "Graduation cap",
    prompt: "a black graduation mortarboard cap with a gold tassel placed on the cat's head",
  },
  {
    id: "chef-hat",
    name: "Chef Cat",
    category: "meme",
    emoji: "👨‍🍳",
    accent: "#f1f5f9",
    description: "Chef's hat",
    prompt: "a tall white chef's toque hat placed on the cat's head",
  },
  {
    id: "monocle",
    name: "Fancy Cat",
    category: "meme",
    emoji: "🎩",
    accent: "#f59e0b",
    description: "Monocle & top hat",
    prompt: "a black top hat placed on the cat's head and a gold monocle on one eye",
  },
  {
    id: "beret",
    name: "French Artist",
    category: "meme",
    emoji: "🖼️",
    accent: "#dc2626",
    description: "Beret & baguette",
    prompt: "a red beret placed on the cat's head and a baguette prop held in one paw",
  },
  {
    id: "viking",
    name: "Viking Cat",
    category: "meme",
    emoji: "⚔️",
    accent: "#9ca3af",
    description: "Viking horns",
    prompt: "a horned Viking helmet placed on the cat's head",
  },
  {
    id: "sunflower",
    name: "Flower Crown",
    category: "meme",
    emoji: "🌸",
    accent: "#f59e0b",
    description: "Flower crown",
    prompt: "a pretty flower crown wreath placed on the cat's head",
  },
  {
    id: "business-cat",
    name: "Business Cat",
    category: "meme",
    emoji: "💼",
    accent: "#1f2937",
    description: "Tie & briefcase",
    prompt: "a small necktie placed around the cat's neck and a tiny briefcase prop placed beside one paw",
  },
  {
    id: "detective-hat",
    name: "Detective",
    category: "meme",
    emoji: "🔍",
    accent: "#4b5563",
    description: "Detective cap",
    prompt: "a brown detective flat cap placed on the cat's head and a small pipe prop near its mouth",
  },

  // ── CRYPTO / WEB3 ───────────────────────────────────────
  {
    id: "bitcoin-chain",
    name: "Bitcoin Maxi",
    category: "crypto",
    emoji: "₿",
    accent: "#f59e0b",
    description: "BTC chain",
    prompt: "a gold Bitcoin BTC chain necklace placed around the cat's neck",
  },
  {
    id: "pepe-hat",
    name: "Pepe",
    category: "crypto",
    emoji: "🐸",
    accent: "#16a34a",
    description: "Pepe frog hat",
    prompt: "a green Pepe the Frog hat prop placed on the cat's head",
  },
  {
    id: "laser-eyes",
    name: "Laser Eyes",
    category: "crypto",
    emoji: "🔴",
    accent: "#dc2626",
    description: "Crypto laser eyes",
    prompt: "bright red glowing laser beam eyes shooting from the cat's eyes like the bitcoin laser eyes meme",
  },
  {
    id: "doge-hat",
    name: "Doge",
    category: "crypto",
    emoji: "🐕",
    accent: "#f59e0b",
    description: "Doge cap",
    prompt: "a bright yellow Doge meme coin cap with the Shiba Inu face placed on the cat's head",
  },
  {
    id: "moon-helmet",
    name: "To The Moon",
    category: "crypto",
    emoji: "🌕",
    accent: "#f59e0b",
    description: "Astronaut helmet",
    prompt: "a white space astronaut helmet placed on the cat's head with a small crescent moon sticker on it",
  },
  {
    id: "diamond-hands",
    name: "Diamond Hands",
    category: "crypto",
    emoji: "💎",
    accent: "#06b6d4",
    description: "Diamond gloves",
    prompt: "sparkling diamond emoji props placed over the cat's two front paws to represent diamond hands",
  },

  // ── HISTORICAL ──────────────────────────────────────────
  {
    id: "napoleon-hat",
    name: "Napoleon",
    category: "historical",
    emoji: "🎩",
    accent: "#1f2937",
    description: "Bicorne hat",
    prompt: "a black Napoleon Bonaparte bicorne hat placed on the cat's head",
  },
  {
    id: "cleopatra",
    name: "Cleopatra",
    category: "historical",
    emoji: "🐍",
    accent: "#f59e0b",
    description: "Egyptian crown",
    prompt: "a gold Egyptian pharaoh Nemes crown with a cobra placed on the cat's head",
  },
  {
    id: "samurai-helmet",
    name: "Samurai",
    category: "historical",
    emoji: "⛩️",
    accent: "#dc2626",
    description: "Samurai helmet",
    prompt: "a traditional Japanese samurai kabuto helmet placed on the cat's head",
  },
  {
    id: "roman-helmet",
    name: "Roman Centurion",
    category: "historical",
    emoji: "🏛️",
    accent: "#dc2626",
    description: "Centurion helmet",
    prompt: "a shiny bronze Roman Centurion galea helmet with a red crest placed on the cat's head",
  },
  {
    id: "musketeer",
    name: "Musketeer",
    category: "historical",
    emoji: "🗡️",
    accent: "#1f2937",
    description: "Musketeer hat",
    prompt: "a wide-brimmed musketeer cavalier hat with a large feather placed on the cat's head",
  },

  // ── HOLIDAY ─────────────────────────────────────────────
  {
    id: "santa-hat",
    name: "Santa",
    category: "holiday",
    emoji: "🎅",
    accent: "#dc2626",
    description: "Santa hat",
    prompt: "a red Santa Claus hat with a white fluffy brim placed on the cat's head",
  },
  {
    id: "reindeer-antlers",
    name: "Reindeer",
    category: "holiday",
    emoji: "🦌",
    accent: "#b45309",
    description: "Reindeer antlers",
    prompt: "brown reindeer antler headband accessories placed on the cat's head",
  },
  {
    id: "halloween-pumpkin",
    name: "Pumpkin",
    category: "holiday",
    emoji: "🎃",
    accent: "#ea580c",
    description: "Jack-o-lantern",
    prompt: "a small carved orange jack-o-lantern pumpkin prop placed beside the cat",
  },
  {
    id: "bunny-ears",
    name: "Easter Bunny",
    category: "holiday",
    emoji: "🐰",
    accent: "#ec4899",
    description: "Bunny ears",
    prompt: "pink Easter bunny ear accessories placed on top of the cat's head",
  },
  {
    id: "birthday-hat",
    name: "Birthday",
    category: "holiday",
    emoji: "🎂",
    accent: "#f43f5e",
    description: "Birthday hat",
    prompt: "a colorful birthday party cone hat with polka dots placed on the cat's head",
  },
];
